<?php
session_start();
include 'database.php'; // Include your database connection

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // Retrieve form data safely
    $username = $_POST["username"];
    $email = $_POST["email"];
    $password = $_POST["password"];
    $confirm_password = $_POST["confirm_password"];
    $role = $_POST["role"];
    $phone_number = isset($_POST["phone_number"]) ? $_POST["phone_number"] : null; // Optional field

    // Validate email
    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        echo "Invalid email address.";
        exit;
    }

    // Validate password
    if (strlen($password) < 8) {
        echo "Password must be at least 8 characters long.";
        exit;
    }

    // Check if passwords match
    if ($password !== $confirm_password) {
        echo "Passwords do not match.";
        exit;
    }

    // Optional phone number validation (simple pattern check)
    if ($phone_number && !preg_match('/^[0-9]{8}$/', $phone_number)) {
        echo "Invalid phone number format. Please enter an 8-digit number.";
        exit;
    }

    // Check if user exists in the database (using prepared statement to prevent SQL injection)
    $data = $conn->prepare("SELECT * FROM user WHERE UserName = ? LIMIT 1");
    $data->bind_param("s", $username);
    $data->execute();
    $result = $data->get_result();

    // If user exists, verify password and log in
    if ($result->num_rows > 0) {
        $user = $result->fetch_assoc();
        // Verify the hashed password
        if (password_verify($password, $user['Password'])) {
            // Correct password, log in the user
            $_SESSION["username"] = $username;
            $_SESSION["role"] = $role;

            // Redirect based on role
            if ($role === "jobseeker") {
                header("Location: jobseeker-home.php");
            } elseif ($role === "employer") {
                header("Location: employerhome.php");
            } else {
                header("Location: admin-home.php");
            }
            exit();
        } else {
            echo "Incorrect password. Please try again.";
            exit();
        }
    } else {
        // If user doesn't exist, insert new user (hash password before storing)
        $hashed_password = password_hash($password, PASSWORD_BCRYPT);
        // Auto-incremented UserID will be generated by the database, so we don't include it in the INSERT query
        $data = $conn->prepare("INSERT INTO user (UserName, Contact, Password, Email, Role) VALUES (?, ?, ?, ?, ?)");
        $data->bind_param("sssss", $username, $phone_number, $hashed_password, $email, $role);

        if ($data->execute()) {
            echo "Registration successful! Logging you in...";

            // Log in the user
            $_SESSION["username"] = $username;
            $_SESSION["role"] = $role;

            // Now, store user details in the respective table
            if ($role === "jobseeker") {
                // Insert into jobseeker table
                $dataJobseeker = $conn->prepare("INSERT INTO jobseeker (FullName, Email, PhoneNumber) VALUES (?, ?, ?)");
                $dataJobseeker->bind_param("sss", $username, $email, $phone_number);
                $dataJobseeker->execute();
                $dataJobseeker->close();
            } elseif ($role === "employer") {
                // Assuming Employer table has Name, Email, PhoneNumber (adjust as needed)
                $dataEmployer = $conn->prepare("INSERT INTO employer (Name, Email, PhoneNumber) VALUES (?, ?, ?)");
                $dataEmployer->bind_param("sss", $username, $email, $phone_number);
                $dataEmployer->execute();
                $dataEmployer->close();
            }

            // Redirect based on role
            if ($role === "jobseeker") {
                header("Location: jobseeker-home.php");
            } elseif ($role === "employer") {
                header("Location: employerhome.php");
            } else {
                header("Location: admin-home.php");
            }
            exit();
        } else {
            echo "Error: " . $data->error;
        }
    }
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>Sign-Up Page</title>
    <link rel="stylesheet" href="css/signin.css">
</head>
<body>
    <div class="container">
        <h2>Sign In to JobQuest !</h2>
        <form method="post" action="signin.php">
            <label for="role">Role:</label>
            <select id="role" name="role" required>
                <option value="jobseeker">Jobseeker</option>
                <option value="employer">Employer</option>
                <option value="admin">Admin</option>
            </select><br><br>

            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required><br><br>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required><br><br>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required><br><br>

            <label for="confirm_password">Confirm Password:</label>
            <input type="password" id="confirm_password" name="confirm_password" required><br><br>

            <label for="phone_number">Phone Number (Optional):</label>
            <input type="tel" id="phone_number" name="phone_number" placeholder="Enter 8-digit phone number"><br><br>

            <input type="submit" value="Sign In">
        </form>
    </div>
</body>
</html>
